"""ednoda-capstone-data package."""

from .schemas import (
    GRAMMAR_REFERENCE_COLUMNS,
    LICENSES_COLUMNS,
    SENTENCES_COLUMNS,
    SOURCE_REGISTRY_COLUMNS,
    VOCABULARY_REFERENCE_COLUMNS,
)

__all__ = [
    "SENTENCES_COLUMNS",
    "VOCABULARY_REFERENCE_COLUMNS",
    "GRAMMAR_REFERENCE_COLUMNS",
    "SOURCE_REGISTRY_COLUMNS",
    "LICENSES_COLUMNS",
]
